server:
  port: 9192

spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/dbtest
#    username: root
#    password: pwd
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: update
  h2:
    console:
      enabled: true
#  main:
#    allow-circular-references: true